name: tao996_example
description: "Demonstrates how to use the tao996 plugin."
publish_to: 'none'

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  tao996:
    path: ../
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_it: ^8.0.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  pull_to_refresh: ^2.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
